### ISSUE TITLE
Comparator function

### ISSUE THREAD

**Issue by radarfox** [moll/js-medium-type#3]
Hello,

I have found an undocumented `MediumType.comparator` in the source code. Is it safe to use? Won't it be removed in some future relase?

It's much more usefull than `MediumType.sort`, which doesn't allow you to sort media types with some additional data.

**Comment by moll** [comment]
Hey there!

I'll get to all of your issues soon, but yeah, `MediumType.comparator` sounds like something that'll remain there. That's why I usually export them so those in-the-know can use them. I guess I was just tired of documenting that I skipped that one. :)
